name: RN SDK CI

on:
    pull_request:
        branches:
            - develop
    push:
        branches:
            - '**'
            - '!master'
        paths-ignore:
            - '**.md'

jobs:
    unit-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install GitHub CLI
              run: |
                  sudo apt-get update
                  sudo apt-get install -y gh jq

            - name: Check for open PR
              id: check_pr
              run: |
                  if [ "${{ github.event_name }}" == "push" ]; then
                    PR_COUNT=$(gh pr list --head "${{ github.ref }}" --state open --json number | jq '. | length')
                    echo "Open PR count: $PR_COUNT"
                    if [ "$PR_COUNT" -eq 0 ]; then
                      echo "No open PR for this branch."
                      exit 1
                    fi
                  fi

            - name: Setup node JS
              uses: actions/setup-node@v2
              with:
                node-version: 14
                registry-url: https://registry.npmjs.org

            - name: Setup local environment
              run: yarn

            - name: Run unit tests
              run: yarn test
