name: PushOk (Develop PR Merge)

on:
  pull_request:
    types: [ closed ]
    branches:
    - 'develop'

jobs:
  call-reusable:
    if: ${{ github.event.pull_request.merged == true }}
    uses: ./.github/workflows/distribute-reusable.yml
    with:
      branch: ${{ github.base_ref }}
    secrets: inherit
