name: Build application after merge

on:
  push:
    branches:
      - 'poziev/gitlab-cicd-port'

jobs:
  trigger:
    runs-on: macos-latest
    #if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get last 3 commit messages
        run: |
          commits=$(git log -3 --pretty=format:"%s")
          echo "commits=$commits" >> $GITHUB_ENV

      - name: trigger build & send to FAD
        run: |
          curl --location 'https://mindbox.gitlab.yandexcloud.net/api/v4/projects/1487/trigger/pipeline' \
            --form 'token="${{ secrets.GITLAB_TRIGGER_TOKEN }}"' \
            --form 'ref="test_branch"' \
            --form "variables[INPUT_BRANCH]=\"${{ github.head_ref }}\"" \
            --form "variables[INPUT_COMMITS]=\"${{ env.commits }}\""
