name: Build pushok

on:
    workflow_call:
        inputs:
            branch:
                required: true
                type: string

jobs:
  trigger:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            ref: ${{ inputs.branch }}

      - name: Get last 3 commit messages
        run: |
          commits=$(git log -3 --pretty=format:"%s")
          echo "commits=$commits" >> $GITHUB_ENV

      - name: Trigger build workflow in react-native-app repo
        run: |
          curl --location 'https://mindbox.gitlab.yandexcloud.net/api/v4/projects/1512/trigger/pipeline' \
            --form 'token="${{ secrets.GITLAB_TRIGGER_TOKEN }}"' \
            --form 'ref="develop"' \
            --form "variables[INPUT_BRANCH]=\"${{ inputs.branch }}\"" \
            --form "variables[INPUT_COMMITS]=\"${{ env.commits }}\""
